use_frameworks!

platform :ios, '9.0'

target 'ConsoliPODS_Example' do
  pod 'ConsoliPODS', :path => '../'

  target 'ConsoliPODS_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
